-- MySQL Script generated by MySQL Workbench
-- Tue Oct 17 23:23:24 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dwclinica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dwclinica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dwclinica` DEFAULT CHARACTER SET utf8 ;
USE `dwclinica` ;

-- -----------------------------------------------------
-- Table `dwclinica`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwclinica`.`empresa` (
  `idempresa` INT(11) NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(20) NULL DEFAULT NULL,
  `nomefantasia` VARCHAR(50) NULL DEFAULT NULL,
  `endereco` VARCHAR(200) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idempresa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dwclinica`.`tempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwclinica`.`tempo` (
  `idtempo` INT(11) NOT NULL AUTO_INCREMENT,
  `dia` INT(2) NOT NULL,
  `mes` INT(2) NOT NULL,
  `ano` INT(5) NOT NULL,
  PRIMARY KEY (`idtempo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dwclinica`.`exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwclinica`.`exame` (
  `idexame` INT(11) NOT NULL AUTO_INCREMENT,
  `idempresa` INT(11) NOT NULL,
  `idtempo` INT(11) NOT NULL,
  `especialidade` VARCHAR(50) NOT NULL,
  `quantidade` INT(11),
  `tipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idexame`),
  INDEX `fktempo_idx` (`idtempo` ASC),
  INDEX `fkempresa_idx` (`idempresa` ASC),
  CONSTRAINT `fkempresa`
    FOREIGN KEY (`idempresa`)
    REFERENCES `dwclinica`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fktempo`
    FOREIGN KEY (`idtempo`)
    REFERENCES `dwclinica`.`tempo` (`idtempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
